package BasicHTML.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int ATag = 0;
  public static final int AbstractTag = 1;
  public static final int BodyTag = 2;
  public static final int CSSList = 3;
  public static final int CSSProperty = 4;
  public static final int DivTag = 5;
  public static final int HTML = 6;
  public static final int HeadTag = 7;
  public static final int PTag = 8;
  public static final int SpanTag = 9;
  public static final int TagList = 10;
  public static final int Text = 11;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L);
    builder.put(0x7e8c85365eb0cc99L, ATag);
    builder.put(0x63ed42a07a666c4dL, AbstractTag);
    builder.put(0x7e8c85365ea03a8aL, BodyTag);
    builder.put(0x7e8c85365ebb1c7eL, CSSList);
    builder.put(0x7e8c85365ebb18d5L, CSSProperty);
    builder.put(0x7e8c85365eaa4d89L, DivTag);
    builder.put(0x63ed42a07a665bedL, HTML);
    builder.put(0x7e8c85365ea590beL, HeadTag);
    builder.put(0x7e8c85365eb31cb7L, PTag);
    builder.put(0x7e8c85365ebb11ebL, SpanTag);
    builder.put(0x63ed42a07a666ff6L, TagList);
    builder.put(0x7e8c85365eb3e5a1L, Text);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
