package BasicHTML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.ConceptKind;
import jetbrains.mps.smodel.runtime.StaticScope;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptATag = createDescriptorForATag();
  /*package*/ final ConceptDescriptor myConceptAbstractTag = createDescriptorForAbstractTag();
  /*package*/ final ConceptDescriptor myConceptBodyTag = createDescriptorForBodyTag();
  /*package*/ final ConceptDescriptor myConceptCSSList = createDescriptorForCSSList();
  /*package*/ final ConceptDescriptor myConceptCSSProperty = createDescriptorForCSSProperty();
  /*package*/ final ConceptDescriptor myConceptDivTag = createDescriptorForDivTag();
  /*package*/ final ConceptDescriptor myConceptHTML = createDescriptorForHTML();
  /*package*/ final ConceptDescriptor myConceptHeadTag = createDescriptorForHeadTag();
  /*package*/ final ConceptDescriptor myConceptPTag = createDescriptorForPTag();
  /*package*/ final ConceptDescriptor myConceptSpanTag = createDescriptorForSpanTag();
  /*package*/ final ConceptDescriptor myConceptTagList = createDescriptorForTagList();
  /*package*/ final ConceptDescriptor myConceptText = createDescriptorForText();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptATag, myConceptAbstractTag, myConceptBodyTag, myConceptCSSList, myConceptCSSProperty, myConceptDivTag, myConceptHTML, myConceptHeadTag, myConceptPTag, myConceptSpanTag, myConceptTagList, myConceptText);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.ATag:
        return myConceptATag;
      case LanguageConceptSwitch.AbstractTag:
        return myConceptAbstractTag;
      case LanguageConceptSwitch.BodyTag:
        return myConceptBodyTag;
      case LanguageConceptSwitch.CSSList:
        return myConceptCSSList;
      case LanguageConceptSwitch.CSSProperty:
        return myConceptCSSProperty;
      case LanguageConceptSwitch.DivTag:
        return myConceptDivTag;
      case LanguageConceptSwitch.HTML:
        return myConceptHTML;
      case LanguageConceptSwitch.HeadTag:
        return myConceptHeadTag;
      case LanguageConceptSwitch.PTag:
        return myConceptPTag;
      case LanguageConceptSwitch.SpanTag:
        return myConceptSpanTag;
      case LanguageConceptSwitch.TagList:
        return myConceptTagList;
      case LanguageConceptSwitch.Text:
        return myConceptText;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForATag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BasicHTML", "ATag", 0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x7e8c85365eb0cc99L);
    b.class_(false, false, false);
    // extends: BasicHTML.structure.AbstractTag
    b.super_(0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x63ed42a07a666c4dL);
    b.origin("r:b26ba3d3-f2e7-4c4d-993e-e78b03bea311(BasicHTML.structure)/9118809814081784985");
    b.version(3);
    b.property("href", 0x7e8c85365eb0d076L).type(PrimitiveTypeId.STRING).origin("9118809814081785974").done();
    b.property("name", 0x7e8c85365eb0d266L).type(PrimitiveTypeId.STRING).origin("9118809814081786470").done();
    b.alias("<a>");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAbstractTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BasicHTML", "AbstractTag", 0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x63ed42a07a666c4dL);
    b.class_(false, true, false);
    b.origin("r:b26ba3d3-f2e7-4c4d-993e-e78b03bea311(BasicHTML.structure)/7200484636251024461");
    b.version(3);
    b.aggregate("body", 0x7e8c85365ea041a7L).target(0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x63ed42a07a666ff6L).optional(false).ordered(true).multiple(false).origin("9118809814080700839").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBodyTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BasicHTML", "BodyTag", 0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x7e8c85365ea03a8aL);
    b.class_(false, false, false);
    // extends: BasicHTML.structure.AbstractTag
    b.super_(0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x63ed42a07a666c4dL);
    b.origin("r:b26ba3d3-f2e7-4c4d-993e-e78b03bea311(BasicHTML.structure)/9118809814080699018");
    b.version(3);
    b.alias("<body>");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCSSList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BasicHTML", "CSSList", 0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x7e8c85365ebb1c7eL);
    b.class_(false, false, false);
    b.origin("r:b26ba3d3-f2e7-4c4d-993e-e78b03bea311(BasicHTML.structure)/9118809814082460798");
    b.version(3);
    b.aggregate("properties", 0x7e8c85365ebb1ea1L).target(0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x7e8c85365ebb18d5L).optional(true).ordered(true).multiple(true).origin("9118809814082461345").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCSSProperty() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BasicHTML", "CSSProperty", 0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x7e8c85365ebb18d5L);
    b.class_(false, false, false);
    b.origin("r:b26ba3d3-f2e7-4c4d-993e-e78b03bea311(BasicHTML.structure)/9118809814082459861");
    b.version(3);
    b.property("name", 0x7e8c85365ebb2aedL).type(PrimitiveTypeId.STRING).origin("9118809814082464493").done();
    b.property("value", 0x7e8c85365ebb2eb1L).type(PrimitiveTypeId.STRING).origin("9118809814082465457").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDivTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BasicHTML", "DivTag", 0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x7e8c85365eaa4d89L);
    b.class_(false, false, false);
    // extends: BasicHTML.structure.AbstractTag
    b.super_(0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x63ed42a07a666c4dL);
    b.origin("r:b26ba3d3-f2e7-4c4d-993e-e78b03bea311(BasicHTML.structure)/9118809814081359241");
    b.version(3);
    b.property("class", 0x7e8c85365eaa53d6L).type(PrimitiveTypeId.STRING).origin("9118809814081360854").done();
    b.alias("<div>");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHTML() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BasicHTML", "HTML", 0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x63ed42a07a665bedL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x12509ddfaa98f128L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b26ba3d3-f2e7-4c4d-993e-e78b03bea311(BasicHTML.structure)/7200484636251020269");
    b.version(3);
    b.aggregate("body", 0x7e8c85365ea2834fL).target(0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x63ed42a07a666ff6L).optional(false).ordered(true).multiple(false).origin("9118809814080848719").done();
    b.kind(ConceptKind.INTERFACE, StaticScope.GLOBAL);
    b.alias("HTML");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHeadTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BasicHTML", "HeadTag", 0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x7e8c85365ea590beL);
    b.class_(false, false, false);
    // extends: BasicHTML.structure.AbstractTag
    b.super_(0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x63ed42a07a666c4dL);
    b.origin("r:b26ba3d3-f2e7-4c4d-993e-e78b03bea311(BasicHTML.structure)/9118809814081048766");
    b.version(3);
    b.alias("<head>");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BasicHTML", "PTag", 0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x7e8c85365eb31cb7L);
    b.class_(false, false, false);
    // extends: BasicHTML.structure.AbstractTag
    b.super_(0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x63ed42a07a666c4dL);
    b.origin("r:b26ba3d3-f2e7-4c4d-993e-e78b03bea311(BasicHTML.structure)/9118809814081936567");
    b.version(3);
    b.alias("<p>");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSpanTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BasicHTML", "SpanTag", 0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x7e8c85365ebb11ebL);
    b.class_(false, false, false);
    // extends: BasicHTML.structure.AbstractTag
    b.super_(0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x63ed42a07a666c4dL);
    b.origin("r:b26ba3d3-f2e7-4c4d-993e-e78b03bea311(BasicHTML.structure)/9118809814082458091");
    b.version(3);
    b.aggregate("style", 0x7e8c85365ebb32c5L).target(0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x7e8c85365ebb1c7eL).optional(true).ordered(true).multiple(false).origin("9118809814082466501").done();
    b.alias("<span>");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTagList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BasicHTML", "TagList", 0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x63ed42a07a666ff6L);
    b.class_(false, false, false);
    b.origin("r:b26ba3d3-f2e7-4c4d-993e-e78b03bea311(BasicHTML.structure)/7200484636251025398");
    b.version(3);
    b.aggregate("body", 0x7e8c85365ea26b55L).target(0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x63ed42a07a666c4dL).optional(true).ordered(true).multiple(true).origin("9118809814080842581").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BasicHTML", "Text", 0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x7e8c85365eb3e5a1L);
    b.class_(false, false, false);
    // extends: BasicHTML.structure.AbstractTag
    b.super_(0x92442f3b2ef5404eL, 0x81cbcaf61a2b4890L, 0x63ed42a07a666c4dL);
    b.origin("r:b26ba3d3-f2e7-4c4d-993e-e78b03bea311(BasicHTML.structure)/9118809814081988001");
    b.version(3);
    b.property("text", 0x7e8c85365eb3eb3fL).type(PrimitiveTypeId.STRING).origin("9118809814081989439").done();
    b.alias("text");
    return b.create();
  }
}
